# Generated by Django 5.2.17 on 2026-10-09 18:10 (manually edited to handle existing rows)

import secrets
import string

from django.db import migrations, models


def _generate_code():
    alphabet = string.ascii_uppercase + string.digits
    suffix = "".join(secrets.choice(alphabet) for _ in range(5))
    return f"MINI-{suffix}"


def populate_access_codes(apps, schema_editor):
    """Back-fill unique access codes for any existing UserDetails rows."""
    UserDetails = apps.get_model('authentication', 'UserDetails')
    existing_codes = set(UserDetails.objects.values_list('access_code', flat=True))

    for user in UserDetails.objects.filter(access_code=''):
        code = _generate_code()
        while code in existing_codes:
            code = _generate_code()
        user.access_code = code
        user.save(update_fields=['access_code'])
        existing_codes.add(code)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        # Step 1: Add the column without the unique constraint so existing rows can be updated
        migrations.AddField(
            model_name='userdetails',
            name='access_code',
            field=models.CharField(blank=True, max_length=20, default=''),
            preserve_default=False,
        ),
        # Step 2: Populate unique codes for existing rows
        migrations.RunPython(populate_access_codes, migrations.RunPython.noop),
        # Step 3: Now it's safe to add the unique constraint
        migrations.AlterField(
            model_name='userdetails',
            name='access_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
