# Generated by Django 5.2.17 on 2026-10-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
