# Generated by Django 5.2.17 on 2026-10-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='avatar_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
